// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamProjectAPI.Data;

#nullable disable

namespace TeamProjectAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423020207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamProjectAPI.Models.BreakfastFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreparationTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BreakfastFoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 350,
                            Cuisine = "American",
                            IsVegetarian = true,
                            Name = "Pancakes",
                            PreparationTime = "20 mins"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 250,
                            Cuisine = "Modern",
                            IsVegetarian = true,
                            Name = "Avocado Toast",
                            PreparationTime = "10 mins"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 500,
                            Cuisine = "Mexican",
                            IsVegetarian = false,
                            Name = "Breakfast Burrito",
                            PreparationTime = "15 mins"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 200,
                            Cuisine = "Mediterranean",
                            IsVegetarian = true,
                            Name = "Greek Yogurt Parfait",
                            PreparationTime = "5 mins"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 600,
                            Cuisine = "American",
                            IsVegetarian = false,
                            Name = "Eggs Benedict",
                            PreparationTime = "25 mins"
                        });
                });

            modelBuilder.Entity("TeamProjectAPI.Models.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresEquipment")
                        .HasColumnType("bit");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Creative",
                            Description = "Capturing moments with a camera",
                            Name = "Photography",
                            RequiresEquipment = true,
                            SkillLevel = 3
                        },
                        new
                        {
                            Id = 2,
                            Category = "Outdoor",
                            Description = "Exploring trails and nature",
                            Name = "Hiking",
                            RequiresEquipment = false,
                            SkillLevel = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = "Indoor",
                            Description = "Strategic board game",
                            Name = "Chess",
                            RequiresEquipment = true,
                            SkillLevel = 4
                        },
                        new
                        {
                            Id = 4,
                            Category = "Creative",
                            Description = "Creating art with paint",
                            Name = "Painting",
                            RequiresEquipment = true,
                            SkillLevel = 3
                        },
                        new
                        {
                            Id = 5,
                            Category = "Indoor",
                            Description = "Playing video games",
                            Name = "Gaming",
                            RequiresEquipment = true,
                            SkillLevel = 5
                        });
                });

            modelBuilder.Entity("TeamProjectAPI.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            Rating = 8.8000000000000007,
                            ReleaseYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Christopher Nolan",
                            Genre = "Action",
                            Rating = 9.0,
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            Rating = 8.5999999999999996,
                            ReleaseYear = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 4,
                            Director = "Bong Joon-ho",
                            Genre = "Thriller",
                            Rating = 8.5,
                            ReleaseYear = 2019,
                            Title = "Parasite"
                        },
                        new
                        {
                            Id = 5,
                            Director = "Frank Darabont",
                            Genre = "Drama",
                            Rating = 9.3000000000000007,
                            ReleaseYear = 1994,
                            Title = "The Shawshank Redemption"
                        });
                });

            modelBuilder.Entity("TeamProjectAPI.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2002, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Computer Information Technology",
                            Email = "rohit.vijai@student.edu",
                            FullName = "Rohit Vijai",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(2001, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Computer Information Technology",
                            Email = "alex.johnson@student.edu",
                            FullName = "Alex Johnson",
                            YearInProgram = "Senior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
